/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;
import atencionresto.* ;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogoResto = new javax.swing.JLabel();
        jNombreUsuario = new javax.swing.JTextField();
        jContraseña = new javax.swing.JPasswordField();
        jIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        registrar = new javax.swing.JPanel();
        jPanelSup = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jVolver = new javax.swing.JButton();
        jLabelP = new javax.swing.JLabel();
        jLabelNU = new javax.swing.JLabel();
        jCrearCuenta = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jRegistrarse = new javax.swing.JButton();
        jNuevoUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jEtiqueta1 = new javax.swing.JLabel();
        jEtiqueta2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_login.setBackground(new java.awt.Color(251, 250, 219));
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\AtencionResto\\src\\imagenes\\linea-02-01.png")); // NOI18N
        panel_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\AtencionResto\\src\\imagenes\\linea-02-01.png")); // NOI18N
        panel_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 20));

        LogoResto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoResto.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\AtencionResto\\src\\imagenes\\resto20px-01.png")); // NOI18N
        panel_login.add(LogoResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 90, 90));

        jNombreUsuario.setBackground(new java.awt.Color(251, 250, 219));
        jNombreUsuario.setFont(new java.awt.Font("Cabin", 0, 12)); // NOI18N
        jNombreUsuario.setForeground(new java.awt.Color(75, 34, 38));
        jNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNombreUsuario.setText("Nombre ");
        jNombreUsuario.setBorder(null);
        panel_login.add(jNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 150, 40));

        jContraseña.setBackground(new java.awt.Color(251, 250, 219));
        jContraseña.setForeground(new java.awt.Color(75, 34, 38));
        jContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jContraseña.setText("jPasswordFie");
        jContraseña.setBorder(null);
        jContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jContraseñaFocusGained(evt);
            }
        });
        panel_login.add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, 40));

        jIniciarSesion.setBackground(new java.awt.Color(251, 250, 219));
        jIniciarSesion.setFont(new java.awt.Font("Cabin", 0, 14)); // NOI18N
        jIniciarSesion.setForeground(new java.awt.Color(75, 34, 38));
        jIniciarSesion.setText("Iniciar Sesion");
        jIniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 34, 38), 5));
        jIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarSesionActionPerformed(evt);
            }
        });
        panel_login.add(jIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 120, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 34, 38));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("o puede ");
        panel_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 60, -1));

        jSeparator1.setForeground(new java.awt.Color(75, 34, 38));
        panel_login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 50, 20));

        jButton3.setBackground(new java.awt.Color(251, 250, 219));
        jButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(75, 34, 38));
        jButton3.setText("registrarse");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_login.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        registrar.setBackground(new java.awt.Color(251, 250, 219));
        registrar.setMinimumSize(new java.awt.Dimension(300, 400));
        registrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSup.setBackground(new java.awt.Color(75, 34, 38));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\AtencionResto\\src\\imagenes\\resto20px-02-01.png")); // NOI18N

        jVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\AtencionResto\\src\\imagenes\\icons8_Back_To_10px.png")); // NOI18N
        jVolver.setBorder(null);
        jVolver.setBorderPainted(false);
        jVolver.setContentAreaFilled(false);
        jVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSupLayout = new javax.swing.GroupLayout(jPanelSup);
        jPanelSup.setLayout(jPanelSupLayout);
        jPanelSupLayout.setHorizontalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addComponent(jVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel5)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanelSupLayout.setVerticalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addComponent(jVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        registrar.add(jPanelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        jLabelP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\AtencionResto\\src\\imagenes\\linea-02-01.png")); // NOI18N
        registrar.add(jLabelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 30));

        jLabelNU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNU.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\AtencionResto\\src\\imagenes\\linea-02-01.png")); // NOI18N
        registrar.add(jLabelNU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 30));

        jCrearCuenta.setFont(new java.awt.Font("Cabin", 0, 14)); // NOI18N
        jCrearCuenta.setForeground(new java.awt.Color(75, 34, 38));
        jCrearCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCrearCuenta.setText("Crear cuenta:");
        registrar.add(jCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 96, 98, 40));
        registrar.add(jSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 300, 10));

        jRegistrarse.setBackground(new java.awt.Color(251, 250, 219));
        jRegistrarse.setFont(new java.awt.Font("Cabin", 0, 14)); // NOI18N
        jRegistrarse.setForeground(new java.awt.Color(75, 34, 38));
        jRegistrarse.setText("Registrarse");
        jRegistrarse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 34, 38), 5));
        jRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistrarseActionPerformed(evt);
            }
        });
        registrar.add(jRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 120, 40));

        jNuevoUsuario.setBackground(new java.awt.Color(251, 250, 219));
        jNuevoUsuario.setFont(new java.awt.Font("Cabin", 0, 11)); // NOI18N
        jNuevoUsuario.setForeground(new java.awt.Color(75, 34, 38));
        jNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNuevoUsuario.setText("Ingrese su nombre");
        jNuevoUsuario.setBorder(null);
        jNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNuevoUsuarioActionPerformed(evt);
            }
        });
        registrar.add(jNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 167, 170, 20));

        jPassword.setBackground(new java.awt.Color(251, 250, 219));
        jPassword.setForeground(new java.awt.Color(75, 34, 38));
        jPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPassword.setText("jPasswordFi**");
        jPassword.setBorder(null);
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
        });
        registrar.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 170, -1));

        jEtiqueta1.setFont(new java.awt.Font("Cabin", 0, 11)); // NOI18N
        jEtiqueta1.setForeground(new java.awt.Color(75, 34, 38));
        jEtiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEtiqueta1.setText("Acontinuacion introduzca su dni");
        registrar.add(jEtiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 160, -1));

        jEtiqueta2.setFont(new java.awt.Font("Cabin", 0, 11)); // NOI18N
        jEtiqueta2.setForeground(new java.awt.Color(75, 34, 38));
        jEtiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEtiqueta2.setText("como contraseña");
        registrar.add(jEtiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistrarseActionPerformed
        // TODO add your handling code here:
        Conexion conexion;
        
        try {
            conexion = new Conexion("jdbc:mysql://localhost/resto", "root", "");
            MeseroData meseroData = new MeseroData(conexion);
            Mesero mesero = new Mesero();
            
            String usuario = jNuevoUsuario.getText();
            mesero.setNombre_mesero(usuario);
            
            int dni = parseInt(jPassword.getText());
            mesero.setDni_mesero(dni);
            
            meseroData.guardarMesero(mesero);
            
            //crear alerta personalizada joptionPane es temporal.
            JOptionPane .showMessageDialog(null,"Usuario registrado");
            
            registrar.setVisible(false);
            panel_login.setVisible(true);
            
        } catch (Exception e) {
            System.out.println("Error al instanciar la clase conexion: " + e.getMessage());
        }
        
     //   registrar.setVisible(false);
     //   panel_login.setVisible(true);
    }//GEN-LAST:event_jRegistrarseActionPerformed

    private void jNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNuevoUsuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        panel_login.setVisible(false);
        registrar.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarSesionActionPerformed
        // TODO add your handling code here:
        Conexion conexion;
        
        try {
            conexion = new Conexion("jdbc:mysql://localhost/resto", "root", "");
            MeseroData meseroData = new MeseroData(conexion);
            Mesero mesero = new Mesero();
            
            String usuario = jNombreUsuario.getText();
            mesero.setNombre_mesero(usuario);
            
            int dni = parseInt(jContraseña.getText());
            mesero.setDni_mesero(dni);
            
            meseroData.logearMesero(usuario, dni);
            
            
        } catch (Exception e) {
            System.out.println("Error al instanciar la clase conexion: " + e.getMessage());
        }
    }//GEN-LAST:event_jIniciarSesionActionPerformed

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        // TODO add your handling code here:
        jPassword.setText("");
    }//GEN-LAST:event_jPasswordFocusGained

    private void jContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jContraseñaFocusGained
        // TODO add your handling code here:
        jContraseña.setText("");
    }//GEN-LAST:event_jContraseñaFocusGained

    private void jVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverActionPerformed
        // TODO add your handling code here:
        registrar.setVisible(false);
        panel_login.setVisible(true);
    }//GEN-LAST:event_jVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoResto;
    private javax.swing.JButton jButton3;
    private javax.swing.JPasswordField jContraseña;
    private javax.swing.JLabel jCrearCuenta;
    private javax.swing.JLabel jEtiqueta1;
    private javax.swing.JLabel jEtiqueta2;
    private javax.swing.JButton jIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNU;
    private javax.swing.JLabel jLabelP;
    private javax.swing.JTextField jNombreUsuario;
    private javax.swing.JTextField jNuevoUsuario;
    private javax.swing.JPanel jPanelSup;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jRegistrarse;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jVolver;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel registrar;
    // End of variables declaration//GEN-END:variables
}
