/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import atencionresto.*;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VistaPedidos extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;
    private DefaultTableModel modeloPedido;
    private DefaultTableModel m;
    private ArrayList <Mesa> listaMesasOcupadas;
    private MesaData mesaData;
    private ProductoData productoData;
    private List<Producto> listaProducto;
    private ArrayList<Mesero> listaMesero;
    private PedidoData pedidoData;
    private Conexion conexion;
    public double total = 0.0;
    private int idMesero;
    
    public VistaPedidos() {
        initComponents();
        
        try {
            conexion = new Conexion("jdbc:mysql://localhost/resto", "root", "");

            modelo = new DefaultTableModel();
            
            modeloPedido = new DefaultTableModel();
            
            mesaData = new MesaData(conexion);
            listaMesasOcupadas = (ArrayList) mesaData.obtenerMesasOcupadas();
            
            productoData = new ProductoData(conexion);
            listaProducto = (ArrayList) productoData.obtenerProductos();
            
            pedidoData = new PedidoData(conexion);
            
            cargarCabeceraProductos();
            cargarCabeceraPedido();
            mostrarMesas();
            mostrarProductos();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void obtenerMesero() {

        String nombre = jNombreMesero.getText();

        MeseroData m = new MeseroData(conexion);
        listaMesero = (ArrayList) m.obtenerMesero(nombre);

        for (Mesero me : listaMesero) {
            idMesero = me.getId_mesero();
            System.out.println("el id del mesero es: " + me.getId_mesero());
        }

    }
    
    public void cargarCabeceraPedido() {
        ArrayList<Object> c = new ArrayList<Object>();
        c.add("Producto");
        c.add("Subtotal");
        c.add("Mesa");
        
        for (Object it : c) {
            modeloPedido.addColumn(it);
        }
        jPedido.setModel(modeloPedido);
    }
    
    public void cargarCabeceraProductos() {
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("Nombre producto");
        columnas.add("Precio");
        
        for (Object it : columnas) {
            modelo.addColumn(it);
        }
        
        jTablaP.setModel(modelo);
    }
    
    public void mostrarProductos() {
            borraFilasTabla();
            
            ProductoData pd = new ProductoData(conexion);
            listaProducto = (ArrayList) pd.obtenerProductos();
            
            for (Producto p : listaProducto ) {
                 modelo.addRow(new Object[]{p.getNombre_producto(),p.getPrecio()});
        }
            
    }
    
    public void borraFilasTabla() {

        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }
    
    public void anularPedido() {
        int a = modeloPedido.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modeloPedido.removeRow(i);
        }
    }
    
    public void mostrarMesas() {
        
            for (Mesa item: listaMesasOcupadas) {
            jMesas.addItem(item.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPedido = new javax.swing.JTable();
        jAgregar = new javax.swing.JButton();
        jBotonCobrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMesas = new javax.swing.JComboBox<>();
        jEtiquetaTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCantidad = new javax.swing.JTextField();
        jEliminar = new javax.swing.JButton();
        jTotal = new javax.swing.JTextField();
        jAnular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jNombreMesero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(251, 250, 219));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vista para gestionar pedidos");

        jTablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablaP);

        jPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jPedido);

        jAgregar.setText("Agregar");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        jBotonCobrar.setText("Guardar pedido");
        jBotonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCobrarActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pedido");

        jMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jEtiquetaTotal.setText("Total:");

        jLabel4.setText("Cantidad");

        jEliminar.setText("Eliminar de la lista");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jAnular.setText("Anular pedido");
        jAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnularActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione una mesa ocupada para gestionar pedido");

        jLabel5.setText("ingrese el nombre del mesero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMesas, 0, 305, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jEtiquetaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTotal))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBotonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jNombreMesero)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEtiquetaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEliminar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAnular))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonCobrar)
                    .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jAgregar)
                    .addComponent(jNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
        // TODO add your handling code here:
        // int filaSeleccionada = tMaterias.getSelectedRow();
        int filaSeleccionada = jTablaP.getSelectedRow();
        try {
            String nombre;
            String precio;
            String subtotal;
            double calcula = 0.0, x = 0.0;
            String cant = "0";
            String mesa;
            
            
            if (filaSeleccionada == -1) {
                JOptionPane .showMessageDialog(null,"Por favor seleccione un producto");
            } else {
                m = new DefaultTableModel();
                m = (DefaultTableModel) jTablaP.getModel();
                nombre = jTablaP.getValueAt(filaSeleccionada, 0).toString();
                precio = jTablaP.getValueAt(filaSeleccionada, 1).toString();
                cant = jCantidad.getText();
                mesa = jMesas.getSelectedItem().toString();
                
                x = (Double.parseDouble(precio) * Integer.parseInt(cant));
                subtotal = String.valueOf(x);
                
                m = (DefaultTableModel) jPedido.getModel();
                String cabecera[] = {nombre,subtotal,mesa};
                m.addRow(cabecera);
            
                calcula = (Double.parseDouble(precio) * Integer.parseInt(jCantidad.getText()));
                total = total + calcula;
                
                jTotal.setText(""+total);
                
                jCantidad.setText("");
            }
            
        } catch (Exception e) {
            JOptionPane .showMessageDialog(null,"Error");
        }
        
    }//GEN-LAST:event_jAgregarActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel m = (DefaultTableModel) jPedido.getModel();
        
        double x = 0.0;
        double precioActual = 0.0;
        double resta = 0.0;
        
        int fila;
        int resp;
        int fil;
        
        try {
            fila = jPedido.getSelectedRow();
            if (fila == -1) {
              JOptionPane .showMessageDialog(null,"Por favor seleccione un producto");  
            } else {
                resta=Double.parseDouble(jPedido.getValueAt(fila,1).toString());
                precioActual = Double.parseDouble(jTotal.getText())-resta;
                total= precioActual;
                jTotal.setText(""+total);
                m.removeRow(fila);
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jBotonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCobrarActionPerformed
        // TODO add your handling code here:
        
        //Busca el id del mesero.
        String nombre = jNombreMesero.getText();

        MeseroData m = new MeseroData(conexion);
        listaMesero = (ArrayList) m.obtenerMesero(nombre);

        for (Mesero me : listaMesero) {
            idMesero = me.getId_mesero();
            
        }
        
        String mesa;
        
        mesa =  jMesas.getSelectedItem().toString();
        
        boolean estado = false;
        
        LocalDate ld = LocalDate.now();
        
        LocalTime lt = LocalTime.now();
        
        LocalDateTime fechaHora = LocalDateTime.of(ld, lt);
        
        pedidoData = new PedidoData(conexion);
        
        pedidoData.guardarPedido(parseInt(mesa), idMesero, total, fechaHora , estado);
        
        mesaData = new MesaData(conexion);
        
        mesaData.actualizarMesaAtendida(parseInt(mesa));
        
    }//GEN-LAST:event_jBotonCobrarActionPerformed

    private void jAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnularActionPerformed
        // TODO add your handling code here:
        anularPedido();
        total= 0.0;
        jTotal.setText(""+total);
    }//GEN-LAST:event_jAnularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregar;
    private javax.swing.JButton jAnular;
    private javax.swing.JButton jBotonCobrar;
    private javax.swing.JTextField jCantidad;
    private javax.swing.JButton jEliminar;
    private javax.swing.JLabel jEtiquetaTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JComboBox<String> jMesas;
    private javax.swing.JTextField jNombreMesero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaP;
    private javax.swing.JTextField jTotal;
    // End of variables declaration//GEN-END:variables
}
